### ISSUE TITLE
POC: maintain only one setup for dev server in angular example

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/luigi#189] opened 2018-11-02 12:22 UTC
*Issue*
We currently have a second development pipeline (Webpack based) because the Angular CLI approach was not able to handle path routing. This is not wanted anymore because of the additional maintenance efforts required and the unnecessary complexity for Luigi users and contributors.

*ToDo*
Use just one development pipeline for the angular example that supports both path and hash routing. We want to keep (if possible) the Angular CLI pipeline and add support for path routing there. It could be that the limitations found in earlier versions of Angular CLI have already been overcome (look [here](https://angular.io/guide/build#rewrite-the-url-path)).

**Comment by parostatkiem** [comment] 2018-11-16 13:04
### Okay, I have to confirm my defeat here :(

I managed to make it working when you are logged-in. If you're not, it does some kind of routing loop.

### What I did:
`<base href="/">` -> _sampleapp.html_


```javascript
providers: [
    LuigiContextService,
    { provide: LocationStrategy, useClass: HashLocationStrategy }
  ],
``` 
and necessary imports of course -> _app.module.ts_

leave `useHash: true` in _app-routing.module.ts_

**Comment by kwiatekus** [comment] 2018-11-20 10:08
The original problem to solve with Angular CLI was being able to reload the page when using path routing

**Comment by parostatkiem** [comment] 2018-11-21 15:11
### My findings

1. [PathRewrite](https://angular.io/guide/build#rewrite-the-url-path) proxy didn't work (tried many configs)
2. [Ngx build plus](https://www.npmjs.com/package/ngx-build-plus/v/7.1.2) didn't work. I tried it with:
-  nearly exactly the same `webpack.conf.js` which we currently use with webpack
- only `historyApiFallback` with different configs
- standard webpack config for Angular

Sadly, it was always redirecting to root when I entered any valid url (or refreshed current page).

**Comment by maxmarkus** [comment] 2018-12-10 16:24
I accidently created a duplicate of this. Duplicate of #287

**Closed** 2018-12-14 10:56 UTC
Labels: area/luigi, duplicate, enhancement
