### ISSUE TITLE
Link Manager: change url but not redirect

### ISSUE THREAD

**Issue by avalkowsky** [kyma-project/luigi#452] opened 2019-04-01 08:42 UTC
**Description**

Hi!

I would like to manipulate the url but not make any real redirect using Link Manager from Luigi Client. 
This is similar to manipulating Location vs. pushing/replacing state on History.

It would be reasonable that it would reflect the history api and both push and replace state functionalities would be on LuigiClient.LinkManager.

**Reasons**

I am using Luigi Client in a setup where my app is an iframe within Luigi Orchestrator.
I would like to change url of the parent app because the resource has been created and I'd love to change url from '/creation-of-new-resource' to '/:newResourceId'.
But I don't want to make a redirect, as it will reload the app. 
The reason is my app is holding some state which will be lost.

It would require much coding to do it manually, for example, store app data in Session Storage, retrieve in in some special case distinguished using some query param, refill the app with data. The app however has a lot of states that are hard to persist/retrieve/set like tab opened, inputs focused and so on. Also the reload takes some time and is not looking great from user perspective.

It would be much simpler to just manipulate url and do nothing more :)

**Comment by maxmarkus** [comment] 2019-04-16 14:47
@avalkowsky closing this ticket, as it was an issue on micro-frontend side.

As far as I remember, we found out, that it was caused by not using a non-standard routing mechanism in the application. Using a proper single page application router on micro-frontend side would make it work as you wished.

If you have the feeling it is still valid, feel free to reach out to me or reopen the ticket.

**Closed by maxmarkus** 2019-04-16 14:47 UTC
Labels: area/luigi
